site_name: ML&AI Learning Collection Site
site_description: Learning Materials
site_author: 'Danny Guo'

theme:
  name: 'material'


copyright: 'Copyright &copy; 2020 Danny Guo'

repo_name: 'GitHub'
docs_dir: docs/
repo_url: https://github.com/VickyGuo0907/ML-AI-learning
edit_uri: edit/master/docs/

# Plugins
plugins:
  - search
# Launch external urls in separate tab
extra_javascript:
  - js/links_in_new_tabs.js
  
markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - meta
  - toc:
      permalink: True
  - attr_list

#Page tree
nav:
  - Home: index.md
  - ML/AI:
    - Machine Learning: ml-ai/ml.md
  - Interviews Preparation:
      - Interview Question: interviews/knowledge.md

