site_name: My Learning Collection Site
site_description: Learning Materials
site_author: 'Danny Guo'

theme:
  name: 'material'


copyright: 'Copyright &copy; 2020 Danny Guo'

repo_name: 'GitHub'
docs_dir: docs/
repo_url: https://github.com/VickyGuo0907/learning-memo
edit_uri: edit/master/docs/

# Plugins
plugins:
  - search

#Page tree
nav:
  - Home: index.md
  - Language:
    - Python:
      - Algorithm: python/python_algorithm.md
      - Panda: python/panda.md
  - Cloud:
    - Kubernetes: cloud/k8s.md
  - ML/AI:
    - Machine Learning: ml-ai/ml.md
  - Interviews Preparation:
      - System Design: interviews/design.md
  - Useful Command:
      - Linux Shell: useful-command/linux-shell.md
      - Docker Command: useful-command/docker.md
      - Helm command: useful-command/helm.md
      - Cloud Related Command: useful-command/cloud-command.md
